# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

integratedExpectation <- function(geneIds, log_alt_guide_probs, log_null_guide_probs, q, p, weights) {
    .Call('_CRISPhieRmix_integratedExpectation', PACKAGE = 'CRISPhieRmix', geneIds, log_alt_guide_probs, log_null_guide_probs, q, p, weights)
}

